### ISSUE TITLE
Spectrogram too Dense

### ISSUE THREAD

**Issue by jayrodge** [thesemicolonguy/audio-to-spectrogram#1]
Hey Sarthak,
Have you made the CNN classifier for this? If yes, can you tell me the details of it.
I'm also working on the project, but the spectrograms generated by this script are too dense to extract the features from. I have tried it and the accuracy is very less.

**Comment by adibyte95** [comment]
use the below script to convert .au file into .wav file 

genres = 0
genre_names = ['blues','classical','country','disco','hiphop','jazz','metal','pop','reggae','rock']

cur_time = time.time()
while genres<10:
    folder_name = genre_names[genres]
    songs = os.listdir('data/' + folder_name)
    print('processing folder: ', folder_name)
    song_number = 0
    while song_number<100:
        filename = songs[song_number]
        path = 'data/'+folder_name+'/'+filename
        song = AudioSegment.from_file(path,'au')
        path_export = 'data_wav/'+folder_name+'/'+str(song_number)+'.wav'
        song.export(path_export,format='wav')
        song_number += 1
    genres +=1
final_time = time.time()
time_taken = final_time - cur_time
print('time taken : ', time_taken/60)

and then generate images using below script

genres = 0
genre_names = ['blues','classical','country','disco','hiphop','jazz','metal','pop','reggae','rock']

cur_time = time.time()
while genres<10:
    folder_name = genre_names[genres]
    songs = os.listdir('data_wav/' + folder_name)
    print('processing folder: ', folder_name)
    song_number = 0
    while song_number<100:
        filename = songs[song_number]
        path = 'data_wav/'+folder_name+'/'+filename
        graph_spectrogram(path,folder_name,song_number)
        song_number += 1
    genres +=1
final_time = time.time()
time_taken = final_time - cur_time
print('time taken : ', time_taken/60)

**Comment by adibyte95** [comment]
more on this here ---> https://github.com/adibyte95/music-genre-classification

**Comment by jayrodge** [comment]
Thanks @adibyte95! 
just wanted to know that is there any difference between converting .au-> spectrogram and .au->.wav->spectrogram?

**Comment by adibyte95** [comment]
@jayrodge  i don't think there is any difference ...not that i know of
